export const projects = [
  {
    id: 'rota-travel-planning-appvima',
    title: 'TravelCini-Tatil Planlama',
    shortTitle: 'TravelCini',
    category: 'Mobile+Web',
    year: '2026',
    role: 'Full Stack Devoloper',
    source: 'Upwork',
    origin: 'Upwork freelance project',
    previewVariant: 'learnlogicify',
    coverImage: '',
    overview:
      'Travelcini flutter,react,figma,firebase gibi teknolojilerle geliştirilmiş bir tatil planlama projesidir, uygulama içinde seyehat planı, yapay zeka desteği,tatil arkadaşı bulma,mesajlaşma gibi fonkısıyonlara sahiptir',
    summary:
      'Avusturalya merkezli bir girişimin fikri olan TravelCini android,ios ve web plaatformu olarak baştan sona geliştirip yayınladım',
    liveUrl: 'https://apps.apple.com/tr/app/travelcini/id6760349777?l=tr',
    githubUrl: 'https://www.travelcini.com/',
    quickStats: [
      { label: 'TimeLine', value: '12 weeks' },
      { label: 'Outcome', value: '88% less drop-off' },
      { label: 'Core tech', value: 'Flutter' },
      { label: 'Source', value: 'Upwork' },
    ],
    problem: {
      tag: '01',
      title: 'Önceki geliştirici başarısız olmuş ve müşteri dolandırılmıştı',
      narrative: 'Proje bana geldiğinde teknık olarak kötü ve müşteriyi kandırma niyetiyle mock verilerle doldurulmuştu',
      points: [
        'Otel ekleme fonksiyonu yoktu',
        "Seyehat planlama müşterinin istediği gibi değildi.",
        'The client said: "Users found the app confusing, so we wanted a much simpler flow."',
      ],
    },
    process: {
      tag: '02',
      title: 'The Process',
      stages: [
        'Analiz:Müşteri ile toplantılar yapılarak proje gereksinimleri toplandı',
        'Tasarım:Figmada ui&ux tasarımı tamamlandı',
        'Geliştirme:Web ve mobil geliştirildi',
        'Dağıtım:Apple ve Google pazarlarında yayınlandı',
        'Marketing:Sosyal medya platformları olusturuldu ve yapay zeka ile video üretildi',
      ],
    },
    tools: ['Figma', 'Maze', 'Spline', 'React Native', 'Expo', 'TypeScript', 'Supabase'],
    solution: {
      tag: '03',
      title: 'A focused mobile flow built around one trip screen.',
      points: [
        'Trip planning, schedule details, and recommendations were unified into one core screen.',
        'A smart suggestion layer reduced the amount of manual user input.',
        'Offline mode supported travelers during unstable connections.',
        'The product centered around three key screens: Home, Create Plan, and Map.',
      ],
    },
    results: {
      tag: '04',
      title: 'The product became easier to start, easier to trust, and easier to keep using.',
      points: [
        'Drop-off decreased by 47%',
        'Session duration increased from 3 minutes to 8 minutes',
        'The app reached a 4.8 App Store rating',
        'Client feedback: "This is exactly what we wanted."',
      ],
    },
    learnings: [
      'User testing should happen at wireframe stage, not later.',
      'Simple navigation consistently wins over feature-heavy flows.',
      'Weekly client check-ins speed up decisions and reduce rework.',
    ],
    stack: {
      design: ['Figma', 'Splinne'],
      development: ['Flutter', 'Supabase', 'React'],
    },
  },
  {
    id: 'yeni-proje-1778072601112',
    title: 'EvimAi Saas Design',
    shortTitle: 'Saas Design',
    category: 'Saas',
    year: '2026',
    role: 'Designer',
    source: '',
    origin: 'Harvard Innovation Labs',
    previewVariant: 'gemini',
    coverImage: '',
    overview:
      'Harvard Innavtion Labs bünyesi altında Gayrimenkul işlerini tek bir paltformda uçtan uca yürütmek amaçlı Saas Projesınde, iş analistliği ve baştan sona web ve mobil olmak üzere 7 aşamada tasarım yaptım.',
    summary: '+120 ekrandan fazla ekran tasarımı , iş analistliği',
    liveUrl: '',
    githubUrl: '',
    quickStats: [
      { label: 'TimeLine', value: '6 weeks' },
      { label: 'Outcome', value: '+120 screens' },
      { label: 'Core tech', value: 'Figma' },
      { label: 'Source', value: 'Harvard Innovation Labs' },
    ],
    problem: {
      tag: '01',
      title: '8 modullü büyük karmaşık projeyi parçalara ayırarak tasarımını yapmak',
      narrative: 'Kafada ve dağınık dokumanlarla belirlenmiş karışık bir projeydi.',
      points: [
        'Farklı modüller arasındaki iş akışlarının tutarsız ve belgesiz olması',
        'Hem web hem mobil olmak üzere 7 aşamada paralel tasarım yapılması gerekiyordu',
        'The project lead said: "We had the vision but needed a designer who could structure and deliver it across 8 complex modules."',
      ],
    },
    process: {
      tag: '02',
      title: 'The Process',
      stages: [
        'Gereksinimlerin Toplanması',
        'İş Analistliği',
        'Tasarım Sisteminin Belirlenmesi',
        'Akışların Çizilmesi',
        'Yüksek Sadakatli Tasarim',
      ],
    },
    tools: ['Claude'],
    solution: {
      tag: '03',
      title: 'A modular design system built to scale across 8 product modules.',
      points: [
        'Business analysis was conducted first to clarify all workflows before design began.',
        'A unified design system was established to maintain consistency across all modules.',
        'Both web and mobile flows were designed in parallel across 7 structured phases.',
      ],
    },
    results: {
      tag: '04',
      title: 'Over 120 screens delivered for a Harvard-backed real estate SaaS.',
      points: [
        '+120 high-fidelity screens delivered across web and mobile',
        'All 8 modules were documented and structured with consistent UX patterns',
        'The client at Harvard Innovation Labs approved the final design system',
      ],
    },
    learnings: [
      'Business analysis before design prevents costly structural rework.',
      'Complex multi-module products need a shared design system from the start.',
      'Phased delivery builds client trust better than delivering everything at once.',
    ],
    stack: {
      design: ['Figma', 'spline', 'adobe'],
      development: [],
    },
  },
  {
    id: 'yeni-proje-1778073997319',
    title: 'Vintage Aİ',
    shortTitle: 'Vintage AI ',
    category: 'Mobile App',
    year: '2025',
    role: 'Mobile Devoloper',
    source: 'Kendi Projem',
    origin: '',
    previewVariant: 'gemini',
    coverImage: '',
    overview:
      'Gemini nanobanana destekli eski fotorğafları yenileme amacıyla geliştirilen projem , revunuecat eklentısı ıle abonelık sistemi,app storede dağıtım ',
    summary: 'Yapay zeka destekli fotoğraf restore etme uygulaması , app storede yayında +300 indirme',
    liveUrl: 'https://apps.apple.com/tr/app/vintage-ai-foto-geli%C5%9Ftirme/id6758045295?l=tr',
    githubUrl: 'https://github.com/Kaandemirrs/VintageApp',
    quickStats: [
      { label: 'TimeLine', value: '1 week' },
      { label: 'Outcome', value: '+300 downloads' },
      { label: 'Core tech', value: 'Flutter' },
      { label: 'Source', value: 'Own product' },
    ],
    problem: {
      tag: '01',
      title: 'Eski fotoğrafları yapay zeka ile canlandıran, hızlı ve minimal bir mobil deneyim',
      narrative:
        'Son teknoloji olan yapay zekaların fotoğraf düzeltme yetkinliğini sezip bende eski fotoğrafları revize eden uygulama geliştirdim',
      points: [
        'Fotoğraf işleme sürecinin kullanıcıya hızlı ve sorunsuz görünmesi gerekiyordu',
        'Yapay zeka API entegrasyonu mobilde stabil ve hızlı çalışmak zorundaydı',
        '',
      ],
    },
    process: {
      tag: '02',
      title: 'The Process',
      stages: ['Gereksınım Belirleme', 'Analiz', 'Tasarım', 'Geliştirme', 'Dağıtım'],
    },
    tools: ['Claude', 'RevenueCat', 'Supabase'],
    solution: {
      tag: '03',
      title: 'A one-tap AI photo restoration app built for speed and simplicity.',
      points: [
        'Users could restore old photos in seconds with a single tap.',
        'The AI integration was wrapped in a clean, minimal interface.',
        'Revenue and subscription flows were handled through RevenueCat.',
      ],
    },
    results: {
      tag: '04',
      title: 'A self-built app on the App Store with over 300 organic downloads.',
      points: [
        '+300 downloads achieved within weeks of launch',
        'The app maintained a strong rating on the App Store',
        'The entire product — from idea to ship — was completed in one week',
      ],
    },
    learnings: [
      'AI features need tight UX wrapping to feel seamless to non-technical users.',
      'A fast build is possible with the right tools and a focused feature set.',
      'Revenue integration should be planned from day one, not added later.',
    ],
    stack: {
      design: ['Figma'],
      development: ['Flutter'],
    },
  },
  {
    id: 'yeni-proje-1778080848825',
    title: 'Loyalty Saas-Restorant Sadakat app',
    shortTitle: 'Loyalty Saas-Restorant Sadakat app',
    category: 'Mobile+Web',
    year: '2025',
    role: 'Full Stack Devoloper',
    source: 'ABD',
    origin: 'upwork',
    previewVariant: 'gemini',
    coverImage: '',
    overview:
      'Restorantlar için ödül sistemli örneğin 5 kahve alana 1 kahve bedava gibi mütşeriyi restoranta sadık yapıcak projemde Amerika texasda dükkan işleten Müşterime uçtan uca dinamik bi şekilde hem restorantı takip ediceği hem müşteri kazanımını sağlıyabilceği proje',
    summary: 'Restorantlar için ödül sistemli sadakat programı',
    liveUrl: 'https://loyalty-pos-app-rho.vercel.app',
    githubUrl: '',
    quickStats: [
      { label: 'TimeLine', value: '6 weeks' },
      { label: 'Outcome', value: 'Full system rebuild' },
      { label: 'Core tech', value: 'Flutter' },
      { label: 'Source', value: 'Upwork' },
    ],
    problem: {
      tag: '01',
      title: 'Önceki geliştirici hem arka hem ön uç olarak bozuk teslim etmişti',
      narrative: 'sıfırdan Flutter ile hem modern hemde ölçeklendirilebilir bir sistem kurdum',
      points: [
        'Tasarımı Figma üzerinden baştan yapıp, admin paneli ve flutter ile geliştirdim',
        'Müşteri gereksinimleri dorğultusunda anlık bağlanma,çark sistemi, ödül ekleme çıkarma gibi özelliklerle dinamik hale getirdim',
        'The client said: "The previous developer left everything broken — we needed a full rebuild from the ground up."',
      ],
    },
    process: {
      tag: '02',
      title: 'The Process',
      stages: ['Gereksinim Analizi', 'Tasarım', 'Geliştirme', 'Canlıya Alma', 'Teslim'],
    },
    tools: ['Claude'],
    solution: {
      tag: '03',
      title: 'A complete system rebuild — new design, new backend, new Flutter app.',
      points: [
        "The entire Figma design was redone from scratch to match the client's brand.",
        'A real-time reward system, spin wheel, and admin panel were built in Flutter.',
        'The backend was restructured to support scalable, dynamic loyalty features.',
      ],
    },
    results: {
      tag: '04',
      title: 'A fully functional loyalty platform rebuilt and delivered in 6 weeks.',
      points: [
        'The previous broken system was replaced with a stable, modern app',
        'All requested features including real-time sync and spin rewards were implemented',
        'The client successfully launched the updated product to restaurant partners',
      ],
    },
    learnings: [
      'Inheriting broken code is often faster to rebuild than repair if the scope allows.',
      'Real-time features like spinning rewards need careful state and sync management.',
      'Always define the full scope with the client before touching any existing code.',
    ],
    stack: {
      design: ['Figma', 'Tailwind'],
      development: ['Flutter', 'React', 'Nodejs'],
    },
  },
  {
    id: 'yeni-proje-1778140835724',
    title: 'YourHill Mobile App',
    shortTitle: 'YourHill Mobile App',
    category: 'Mobile App',
    year: '2026',
    role: 'Mobile Devoloper',
    source: 'Freelence',
    origin: 'Upwork',
    previewVariant: 'gemini',
    coverImage: '',
    overview: 'Tasarımı ve Geliştiriciliğini yaptıgım Freelence Projem',
    summary: 'Sosyal iletişim uygulaması , politika ile oy verme , görüş bildirme, anket olusturma',
    liveUrl: 'https://www.figma.com/design/bjhTrTgzLY0Qr6NuyHz7tg/YourHill?node-id=1-5&t=AkQ6zpOwF3hYF3vx-1',
    githubUrl: '',
    quickStats: [
      { label: 'TimeLine', value: '6 weeks' },
      { label: 'Outcome', value: 'Delivered on time' },
      { label: 'Core tech', value: 'Flutter' },
      { label: 'Source', value: 'Upwork' },
    ],
    problem: {
      tag: '01',
      title: 'Sosyal iletişim platformu için modüler ve sezgisel bir mobil deneyim gerekiyordu',
      narrative:
        'Politika, oy verme ve anket gibi farklı özellikleri tek bir akıcı uygulamada birleştirmek karmaşık bir mimari gerektirdi',
      points: [
        'Farklı kullanıcı modülleri arasında geçiş tutarsız ve karmaşıktı',
        'Anket ve oy sistemi gerçek zamanlı veri güncellemeleri gerektiriyordu',
        'The client said: "We needed one clean app where users could share opinions, vote, and engage — without getting lost."',
      ],
    },
    process: {
      tag: '02',
      title: 'The Process',
      stages: ['Analiz', 'İŞ akışları Belirleme', 'Tasarım', 'Geliştirme', 'Dağıtım'],
    },
    tools: ['Claude', 'Figma'],
    solution: {
      tag: '03',
      title: 'A unified social app connecting political engagement with community interaction.',
      points: [
        'Poll, vote, and opinion features were merged into one cohesive flow.',
        'Real-time sync kept political content up to date across all users.',
        'Clean navigation made the app accessible to users of all technical levels.',
      ],
    },
    results: {
      tag: '04',
      title: 'A functional social platform delivered on time with full feature coverage.',
      points: [
        'All three core modules were integrated into a single smooth experience',
        'Client approved the final build without revision requests',
        'The app was ready for deployment at the end of the 6-week timeline',
      ],
    },
    learnings: [
      'Modular state management is essential for multi-feature social apps.',
      'Real-time features need early architectural decisions.',
      'Simple navigation always beats complex feature hierarchies.',
    ],
    stack: {
      design: ['Figma'],
      development: ['Flutter'],
    },
  },
  {
    id: 'yeni-proje-1778082022669',
    title: 'Beykent Üniversitesi Web sitesi ve mobil uygulaması',
    shortTitle: 'Beykent Üniversitesi web sitesi ve mobil uygulaması',
    category: 'Mobile App + Web Sitesi',
    year: '2025',
    role: 'Full Stack Devoloper',
    source: '',
    origin: 'Okuldan',
    previewVariant: 'gemini',
    coverImage: '',
    overview:
      'Karmaşık,dinamik olmayan ve tasarımında eleştirilcek kısımları olan web sitesini ekip arkdaşlarımla birlikte baştan sonra yaptık ve sıfırdan mobil uygulamayıda.(Canlıda Değil)',
    summary: 'Okulun web sitesi ve olmayan mobil uygulamasını ekip arkadaşlarımla birlikte yaptık',
    liveUrl: '',
    githubUrl: '',
    quickStats: [
      { label: 'TimeLine', value: '12 months' },
      { label: 'Outcome', value: '2 platforms built' },
      { label: 'Core tech', value: 'React' },
      { label: 'Source', value: 'University' },
    ],
    problem: {
      tag: '01',
      title: 'Üniversitenin dijital varlığı hem web hem mobil olmak üzere yeniden yapılandırılması gerekiyordu',
      narrative: 'Tasarımı modern olmayan ve ux karmaşası olan web sitesi',
      points: [
        'Okulun mobil uygulamasının olmaması',
        'Web sitesinin dinamik ve sürdürülebilir bir altyapısı olmaması',
        'The department said: "Students needed a modern digital experience on both web and mobile to access campus resources efficiently."',
      ],
    },
    process: {
      tag: '02',
      title: 'The Process',
      stages: ['Ekip Oluşturma ve Rol Belirleme', 'Gereksinim analizi', 'Tasarım', 'Geliştirme', 'Teslim'],
    },
    tools: ['Claude'],
    solution: {
      tag: '03',
      title: 'A modern university web platform and a first-ever campus mobile app.',
      points: [
        'The web platform was rebuilt with a dynamic, maintainable architecture.',
        "A brand-new mobile app brought campus resources to students' fingertips.",
        'The team coordinated roles and responsibilities across a 12-month academic sprint.',
      ],
    },
    results: {
      tag: '04',
      title: 'Two fully delivered digital products for the university, built as a team.',
      points: [
        'The web platform was modernized with consistent UX and a fresh design',
        'The mobile app filled a long-standing gap in the student experience',
        'The project was completed across a 12-month development cycle',
      ],
    },
    learnings: [
      'Team coordination across roles requires clear scope boundaries from day one.',
      'University systems have complex content structures that need modular design.',
      'A 12-month timeline needs regular milestone reviews to stay on track.',
    ],
    stack: {
      design: ['Figma', 'Stitch'],
      development: ['React', 'Python', 'Kotlin', 'CSS'],
    },
  },
]

export const skills = [
  {
    group: 'design',
    items: ['UI Design', 'UX Thinking', 'Wireframing'],
  },
  {
    group: 'development',
    items: ['React', 'Tailwind CSS', 'JavaScript'],
  },
]
